services:
  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: ghcr.io/tursodatabase/libsql-server:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./apps/api/.env
    environment:
      TURSO_DATABASE_URL: ${TURSO_DATABASE_URL}
      TURSO_AUTH_TOKEN: ${TURSO_AUTH_TOKEN}